zeebe:
  client:
    cloud:
      cluster-id:
      client-id:
      client-secret:
      region:
    security:
      enabled: false
    broker:
      gateway-address: 
spring:
  main:
    web-application-type: none
camunda:
  connector:
    webhook:
      enabled: false
    polling:
      enabled: false
